//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRC_WEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NrcDbContext : DbContext
    {
        public NrcDbContext() 
            : base("name=NrcCloudDbContext")
            //: base("name=NrcDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<ScheduleDayOfTheWeek> ScheduleDayOfTheWeeks { get; set; }
        public virtual DbSet<ScheduleStation> ScheduleStations { get; set; }
        public virtual DbSet<Station> Stations { get; set; }
        public virtual DbSet<TrainType> TrainTypes { get; set; }
        public virtual DbSet<TrainTypeTravelClass> TrainTypeTravelClasses { get; set; }
        public virtual DbSet<TravelClass> TravelClasses { get; set; }
        public virtual DbSet<ScheduleTravelClass> ScheduleTravelClasses { get; set; }
        public virtual DbSet<DayOfTheWeek> DayOfTheWeeks { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
    }
}
