//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRC_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleTravelClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleTravelClass()
        {
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int Id { get; set; }
        public int ScheduleId { get; set; }
        public int TravelClassId { get; set; }
        public int NumberOfSeats { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual TravelClass TravelClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
