//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRC_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDayOfTheWeek
    {
        public int Id { get; set; }
        public int ScheduleId { get; set; }
        public int DayOfTheWeekId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual DayOfTheWeek DayOfTheWeek { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
