//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NRC_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainTypeTravelClass
    {
        public int Id { get; set; }
        public Nullable<int> TrainTypeId { get; set; }
        public Nullable<int> TravelClassId { get; set; }
        public Nullable<int> NumberOfSeats { get; set; }
    
        public virtual TrainType TrainType { get; set; }
        public virtual TravelClass TravelClass { get; set; }
    }
}
